baseURL = 'https://lbslightx.github.io/reaper/'
languageCode = 'en-ca'
title = 'Untitled Project'
theme = 'retroish'

[markup.goldmark.renderer]
unsafe = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

# Uncomment when there are actual posts
#[[menus.main]]
#name = 'Posts'
#pageRef = '/posts'
#weight = 20
