baseURL = 'https://biribiri.dev/'
languageCode = 'en-ca'
title = 'âš¡ Project Radio Noise ðŸ”Œ'
theme = 'retroish'

[markup.goldmark.renderer]
unsafe = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

# Uncomment when there are actual posts
#[[menus.main]]
#name = 'Posts'
#pageRef = '/posts'
#weight = 20